-- 电池SaaS平台数据库初始化脚本

-- 创建数据库（如果不存在）
CREATE DATABASE IF NOT EXISTS battery_saas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 使用数据库
USE battery_saas;

-- 创建租户表（SaaS多租户基础表）
CREATE TABLE IF NOT EXISTS tenants (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_code VARCHAR(50) NOT NULL UNIQUE COMMENT '租户编码',
    name VARCHAR(100) NOT NULL COMMENT '租户名称',
    domain VARCHAR(100) UNIQUE COMMENT '域名',
    contact_person VARCHAR(50) COMMENT '联系人',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    contact_email VARCHAR(120) COMMENT '联系邮箱',
    status ENUM('active', 'inactive', 'suspended') DEFAULT 'active' COMMENT '状态',
    max_users INT DEFAULT 100 COMMENT '最大用户数',
    max_stations INT DEFAULT 50 COMMENT '最大站点数',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    INDEX idx_tenant_code (tenant_code),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户表';

-- 插入默认租户
INSERT INTO tenants (tenant_code, name, domain) VALUES
('default', '默认租户', 'default.battery-saas.com')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- 创建用户表
CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL DEFAULT 1,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(120),
    phone VARCHAR(20) NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    avatar VARCHAR(500),
    nickname VARCHAR(50),
    real_name VARCHAR(50),
    gender ENUM('male', 'female', 'unknown') DEFAULT 'unknown',
    birth_date DATE,
    is_active BOOLEAN DEFAULT TRUE,
    is_verified BOOLEAN DEFAULT FALSE,
    last_login_at DATETIME,
    is_rider BOOLEAN DEFAULT FALSE,
    rider_level ENUM('bronze', 'silver', 'gold', 'platinum') DEFAULT 'bronze',
    work_status ENUM('offline', 'online', 'busy') DEFAULT 'offline',
    points INT DEFAULT 0,
    balance DECIMAL(10,2) DEFAULT 0.00,
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    location_updated_at DATETIME,
    device_id VARCHAR(100),
    push_token VARCHAR(500),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    UNIQUE KEY uk_tenant_username (tenant_id, username),
    UNIQUE KEY uk_tenant_phone (tenant_id, phone),
    UNIQUE KEY uk_tenant_email (tenant_id, email),
    INDEX idx_tenant_id (tenant_id),
    INDEX idx_phone (phone),
    INDEX idx_is_rider (is_rider),
    INDEX idx_work_status (work_status),
    INDEX idx_location (latitude, longitude),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- 创建站点表
CREATE TABLE IF NOT EXISTS stations (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL DEFAULT 1,
    station_code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    type ENUM('street', 'mall', 'office', 'residential', 'parking') DEFAULT 'street',
    status ENUM('active', 'maintenance', 'inactive') DEFAULT 'active',
    latitude DECIMAL(10,7) NOT NULL,
    longitude DECIMAL(10,7) NOT NULL,
    address VARCHAR(500) NOT NULL,
    city VARCHAR(50),
    district VARCHAR(50),
    open_time TIME,
    close_time TIME,
    is_24_hour BOOLEAN DEFAULT FALSE,
    total_cabinets INT DEFAULT 0,
    total_slots INT DEFAULT 0,
    available_slots INT DEFAULT 0,
    total_batteries INT DEFAULT 0,
    available_batteries INT DEFAULT 0,
    charging_batteries INT DEFAULT 0,
    monthly_rentals INT DEFAULT 0,
    monthly_revenue DECIMAL(12,2) DEFAULT 0.00,
    network_status BOOLEAN DEFAULT TRUE,
    last_heartbeat DATETIME,
    firmware_version VARCHAR(20),
    images JSON,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    UNIQUE KEY uk_tenant_station_code (tenant_id, station_code),
    INDEX idx_tenant_id (tenant_id),
    INDEX idx_status (status),
    INDEX idx_location (latitude, longitude),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='充电换电站点表';

-- 创建柜子表
CREATE TABLE IF NOT EXISTS cabinets (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL DEFAULT 1,
    cabinet_code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    model VARCHAR(50),
    station_id INT NOT NULL,
    status ENUM('online', 'offline', 'maintenance', 'fault') DEFAULT 'online',
    temperature DECIMAL(5,1),
    humidity DECIMAL(5,1),
    total_slots INT DEFAULT 20,
    occupied_slots INT DEFAULT 0,
    available_slots INT DEFAULT 20,
    battery_count INT DEFAULT 0,
    imei VARCHAR(50),
    ip_address VARCHAR(20),
    mac_address VARCHAR(20),
    firmware_version VARCHAR(20),
    network_signal INT,
    last_heartbeat DATETIME,
    is_online BOOLEAN DEFAULT TRUE,
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    UNIQUE KEY uk_tenant_cabinet_code (tenant_id, cabinet_code),
    INDEX idx_tenant_id (tenant_id),
    INDEX idx_station_id (station_id),
    INDEX idx_status (status),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (station_id) REFERENCES stations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='电池柜子表';

-- 创建电池表
CREATE TABLE IF NOT EXISTS batteries (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL DEFAULT 1,
    battery_code VARCHAR(50) NOT NULL,
    battery_type ENUM('lithium_ion', 'lithium_polymer', 'lead_acid') DEFAULT 'lithium_ion',
    model VARCHAR(100) NOT NULL,
    capacity INT NOT NULL COMMENT '容量(mAh)',
    status ENUM('available', 'in_use', 'charging', 'maintenance', 'scrapped') DEFAULT 'available',
    power_level INT DEFAULT 100 COMMENT '电量百分比(0-100)',
    voltage DECIMAL(5,2),
    temperature DECIMAL(5,1),
    current_station_id INT,
    current_cabinet_id INT,
    slot_position VARCHAR(20),
    current_user_id INT,
    rented_at DATETIME,
    expected_return_at DATETIME,
    last_maintenance_at DATETIME,
    next_maintenance_at DATETIME,
    maintenance_count INT DEFAULT 0,
    purchase_date DATE,
    warranty_period INT DEFAULT 24 COMMENT '质保期(月)',
    total_usage_hours INT DEFAULT 0,
    cycle_count INT DEFAULT 0,
    rental_price_per_hour DECIMAL(8,2) DEFAULT 0.50,
    deposit_amount DECIMAL(8,2) DEFAULT 50.00,
    imei VARCHAR(50),
    bluetooth_mac VARCHAR(20),
    firmware_version VARCHAR(20),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    UNIQUE KEY uk_tenant_battery_code (tenant_id, battery_code),
    INDEX idx_tenant_id (tenant_id),
    INDEX idx_status (status),
    INDEX idx_current_station (current_station_id),
    INDEX idx_current_cabinet (current_cabinet_id),
    INDEX idx_current_user (current_user_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (current_station_id) REFERENCES stations(id),
    FOREIGN KEY (current_cabinet_id) REFERENCES cabinets(id),
    FOREIGN KEY (current_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='电池表';

-- 创建订单表
CREATE TABLE IF NOT EXISTS orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL DEFAULT 1,
    order_no VARCHAR(50) NOT NULL,
    order_type ENUM('rental', 'purchase', 'exchange') NOT NULL,
    status ENUM('pending', 'paid', 'rented', 'returned', 'completed', 'cancelled', 'refunded') DEFAULT 'pending',
    user_id INT NOT NULL,
    battery_id INT,
    station_id INT,
    cabinet_id INT,
    rental_start_time DATETIME,
    rental_end_time DATETIME,
    expected_return_time DATETIME,
    actual_return_time DATETIME,
    rental_hours INT DEFAULT 24,
    unit_price DECIMAL(8,2),
    rental_fee DECIMAL(8,2) DEFAULT 0.00,
    deposit_fee DECIMAL(8,2) DEFAULT 0.00,
    total_amount DECIMAL(8,2) DEFAULT 0.00,
    payment_method VARCHAR(20),
    payment_time DATETIME,
    transaction_id VARCHAR(100),
    refund_amount DECIMAL(8,2) DEFAULT 0.00,
    refund_time DATETIME,
    refund_reason VARCHAR(200),
    pickup_location VARCHAR(500),
    return_location VARCHAR(500),
    pickup_latitude DECIMAL(10,7),
    pickup_longitude DECIMAL(10,7),
    return_latitude DECIMAL(10,7),
    return_longitude DECIMAL(10,7),
    remarks TEXT,
    cancel_reason VARCHAR(200),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    UNIQUE KEY uk_tenant_order_no (tenant_id, order_no),
    INDEX idx_tenant_id (tenant_id),
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_order_type (order_type),
    INDEX idx_battery_id (battery_id),
    INDEX idx_station_id (station_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (battery_id) REFERENCES batteries(id),
    FOREIGN KEY (station_id) REFERENCES stations(id),
    FOREIGN KEY (cabinet_id) REFERENCES cabinets(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单表';

-- 创建支付表
CREATE TABLE IF NOT EXISTS payments (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL DEFAULT 1,
    payment_no VARCHAR(50) NOT NULL,
    payment_type ENUM('order_payment', 'deposit_refund', 'penalty', 'recharge') NOT NULL,
    payment_method ENUM('wechat', 'alipay', 'balance', 'card') NOT NULL,
    status ENUM('pending', 'success', 'failed', 'refunded', 'cancelled') DEFAULT 'pending',
    user_id INT NOT NULL,
    order_id INT,
    amount DECIMAL(10,2) NOT NULL,
    refund_amount DECIMAL(10,2) DEFAULT 0.00,
    transaction_id VARCHAR(100),
    out_trade_no VARCHAR(100),
    prepay_id VARCHAR(100),
    payment_time DATETIME,
    refund_time DATETIME,
    payment_params JSON,
    callback_data JSON,
    remarks VARCHAR(500),
    error_message VARCHAR(500),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    UNIQUE KEY uk_tenant_payment_no (tenant_id, payment_no),
    INDEX idx_tenant_id (tenant_id),
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_payment_type (payment_type),
    INDEX idx_order_id (order_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付记录表';

